//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skypebot.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ChatSubscriptions = new HashSet<ChatSubscription>();
            this.Resources = new HashSet<Resource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
    
        public virtual ICollection<ChatSubscription> ChatSubscriptions { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
